### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by sanskar783**
sir i have only added the to your project for completing my tasks as i have to pull 4 request please let me do so

### CODE REVIEW

**Comment by AirFusion45** [comment]
Most likely spam:

ref:
https://github.com/pgRouting/website/pull/92
https://github.com/v-iashin/WebsiteYOLO/pull/45
https://github.com/bitcraze/bitcraze-website/pull/69

In response to the increased spam due to hacktoberfest I am going around and marking pulls that are potential spams with the keyword "spam" in comments - so hopefully it allows contributors to just search "spam" and all the spam pulls will be there for them to close and lock.

**Comment by rndmh3ro** [comment]
> In response to the increased spam due to hacktoberfest I am going around and marking pulls that are potential spams with the keyword "spam" in comments - so hopefully it allows contributors to just search "spam" and all the spam pulls will be there for them to close and lock.

Use a "spam" label.

**Comment by ibennetch** [comment]
Hi,

Thanks for making an effort to improve the readability of something here. Unfortunately, I don't think your change is needed; adding a "the" subtly changes the meaning of the sentence in a way I don't think is needed. Perhaps there's another change you see that could improve our phrasing.

**Comment by sanskar783** [comment]
Yes sir I will look into matter and thanks for your reply your reply is solicited and will be solicited actually thing is that I was completing a task in which I have to go for 4 pull request I loved your programs and it was perfect too but for completing a task I thought adding a ‘the would not create an issue .Thank You sir .  SANSKAR SHARMAClass 8 JAIPURINDIA Sent from Mail for Windows 10 From: Isaac BennetchSent: 02 October 2020 15:32To: phpmyadmin/websiteCc: sanskar783; AuthorSubject: Re: [phpmyadmin/website] Update README.rst (#123) Hi,Thanks for making an effort to improve the readability of something here. Unfortunately, I don't think your change is needed; adding a "the" subtly changes the meaning of the sentence in a way I don't think is needed. Perhaps there's another change you see that could improve our phrasing.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request closed without merging**
