### PR TITLE
Upgrade website to be compatible with Python3

### PR DESCRIPTION
**Pull request by ibennetch**
This series of commits should upgrade the website to Python3 compatibility.

It doesn't automatically upgrade the software running on the server, so before merging we should be ready to perform the appropriate software installation/reconfiguration. I believe that merging this while still on Python2 will break the site. As a result, this is currently a draft pull request.

Closes: https://github.com/phpmyadmin/website/issues/132

### CODE REVIEW

**Comment by ibennetch** [comment]
Remaining items to do:
- [ ] Modify settings.py (at least the `MIDDLEWARE` directive becomes `MIDDLEWARE_CLASSES` and needs `'django.contrib.auth.middleware.SessionAuthenticationMiddleware',` added)
- [ ] Prepare the server with the proper Python3 requirements

**Review by mauriciofauth — APPROVED** [review]
:clap: :100:

**Review by williamdes — APPROVED** [review]
:100:

Closes: #132

**Comment by williamdes** [comment]
Ready to be merged ?

**Comment by williamdes** [comment]
> Ready to be merged ?

Tests are still failing: https://github.com/phpmyadmin/website/runs/1835861700#step:8:7

**Comment by MauricioFauth** [comment]
Hi, any update on this?

**Comment by MauricioFauth** [comment]
The tests are broken since a180276096e55ca1d4fc03191a3b497bbafc9ec7.

**Review by williamdes — APPROVED** [review]
👀 💯

**Comment by MauricioFauth** [comment]
@ibennetch @williamdes Tests are now passing on this PR. I think it can be merged if the server has Python 3.7 installed (as it's the [last version support by Django 1.11](https://docs.djangoproject.com/en/1.11/faq/install/#faq-python-version-support)). This way we can work on upgrading the Django version.

**Comment by ibennetch** [comment]
Great, thanks for the work on this. Yes, 3.7 is installed, although not the
default when calling /bin/env python so it might need a tweak to update for
that

I'm not merging it right now because I don't have time tonight to fix
anything if there are migration problems, so I'll hold off until I (or
someone else) has time to devote to that, but I think it's ready to merge.

**Pull request merged**
