### PR TITLE
improve docs

### PR DESCRIPTION
**Pull request by harshsoni123**

### CODE REVIEW

**Comment by ibennetch** [comment]
Hi,

Thanks for your interest in contributing to the phpMyAdmin project. I'm not sure how the RST standard handles line breaks in a heading, does this render correctly? I also don't feel we should add such self-serving comments in the license information.

Is this work for a school/university project?

Regards,
Isaac from the phpMyAdmin team

**Comment by harshsoni123** [comment]
Can u plz accept my pull request.

**Comment by ibennetch** [comment]
I don't feel like you've addressed any of the concerns I've brought up, so I don't feel this is ready to merge at this time.

Did you test the rendering of the heading in the rendered RST file?

**Comment by mauriciofauth** [comment]
If you believe that closing this pull request was a mistake, please reply to this message.

**Pull request closed without merging**
