### PR TITLE
Document not acceptable sites

### PR DESCRIPTION
**Pull request by nijel**
As agreed on the team meeting, see
https://irc.phpmyadmin.net/meetbot/phpmyadmin/2016/phpmyadmin.2016-11-09-12.16.html

Signed-off-by: Michal Čihař <michal@cihar.com>

### CODE REVIEW

**Comment by nijel** [comment]
Comments welcome from @phpmyadmin/developers :-)

**Comment by ibennetch** [comment]
Looks good now.

**Comment by ibennetch** [comment]
I prefer an "Oxford Comma" — one more comma before the "or" at the end of the list, but that's very much a stylistic preference.

**Comment by nijel** [comment]
Added ... I still wonder whether the "Since December 2016" should be there. It might say that before we did accept all of that what is not true.

**Comment by ibennetch** [comment]
I also wondered about the text; it's sort of good because we have some sponsors who are still in the middle of their terms, and that text shows when we cut those sponsors off and makes clear that we don't do it anymore. On the other hand, it doesn't really add a whole lot to the text, either.

I think the optimal way to handle it is to leave "Since December 2016" for now, and then to remove that part once the last sponsorship of these types expires. It means a bit more for us to remember in a few months, but for me that's the best way to handle it.

**Comment by nijel** [comment]
Okay, I've merged it and should be live in few minutes.

**Pull request merged**
