### PR TITLE
Download popup

### LINKED ISSUE #17: Suggesting a donation on download
As discussed on https://github.com/phpmyadmin/phpmyadmin/wiki/2016-01_Meeting#suggesting-a-donation-amount we would display "We hope you enjoy phpMyAdmin. Please consider donating to support our development (suggested amount: 10 USD)." after a download (either on the download button or links).

### PR DESCRIPTION
**Pull request by nijel**
Note: This pull request is on top of #22 (it only adds two commits on top of that).

Add popup after user clicked on download
    
This popup covers two topic:
    
- encourages users to verify downloaded file (either by SHA sums or by      PGP)
- suggests donating to phpMyAdmin (fixes #17)

See screenshot:

phpmyadmin_-_2016-08-05_11 18 13

### CODE REVIEW

**Comment by nijel** [comment]
Any objections to merging this? @ibennetch or @madhuracj :-)

**Comment by ibennetch** [comment]
I'm not a big fan of extra popups when downloading, but this isn't too obtrusive. I don't have a strong opinion about this either way.

**Comment by nijel** [comment]
Main motivation was to highlight ways of checking download even for download button on main page. Also this nicely accommodates #17. 

On the other side maybe this is just too obtrusive as vast majority of people will just ignore both things :-). That's why I've created this PR separately on top of other changes.

**Comment by madhuracj** [comment]
I do not think it's too obtrusive. So, I am in favor.

**Comment by ibennetch** [comment]
Okay, let's go ahead with merging it.

**Comment by nijel** [comment]
Okay, merged!

**Pull request merged**
