### PR TITLE
Bootstrap version of website

### PR DESCRIPTION
**Pull request by nijel**
Rewritten website using jQuery and Bootstrap. Major changes:

* Responsive layout, works well on small screens as well
* Moved action buttons to white space next to headline
* Grouped PMASA listing by year to better handle amount of entries we're having
* More consistent UI in things such as theme downloads

### CODE REVIEW

**Comment by nijel** [comment]
Here is preview of current look, comments welcome:

phpmyadmin_-_security_-_pmasa-2015-3_-_2016-08-01_16 52 55

phpmyadmin_-_2016-08-01_16 52 39

phpmyadmin_-_2016-08-01_16 49 15

I know there are still several things missing in new layout, but this is just to give rough idea.

**Comment by nijel** [comment]
I think it's now ready for merge :-).

**Comment by devenbansod** [comment]
Hi, 
I don't if it makes sense, but does moving the 4 buttons in the header slightly towards left (like in center of the announcements div below it) look better or the original one is fine ? 

Moved one:
security_moved

Original one:
security_orignal

**Comment by nijel** [comment]
Good idea, I've adjusted the buttons to use same layout as content:

phpmyadmin_-_security_-_2016-08-05_14 55 00

**Comment by nijel** [comment]
Any objections to merging this? @ibennetch or @madhuracj :-)

**Comment by ibennetch** [comment]
No objections, go right ahead. Nice work.

**Comment by madhuracj** [comment]
Looks good. Go ahead and merge.

**Pull request merged**
