### PR TITLE
Upgrade Bootstrap and jQuery

### LINKED ISSUE #131: Upgrade Bootstrap
The phpMyAdmin website is currently using the Bootstrap v3.3.7. We should upgrade it to the latest version.

### PR DESCRIPTION
**Pull request by mauriciofauth**
- Upgrades Bootstrap to v4.5.3
- Upgrades jQuery to v3.5.1

Fixes #131.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Screenshot from 2020-10-14 14-59-45

**Review by williamdes — APPROVED** [review]
It looks clean !

**Comment by ibennetch** [comment]
This seems to cause a display issue with the hamburger menu, at least on iOS.

image

**Comment by mauriciofauth** [comment]
Thank you for noticing that. I will fix it as soon as possible.

**Pull request merged**
